### pythonインタープリタとして機能するdocker imageを作成するDockerfile

FROM python:3.7

RUN apt-get update
RUN apt-get install -y gosu

### python環境構築
ADD requirements.txt .
RUN pip install -r requirements.txt

### build時に引数として与えられたuname、uid、gidから一般ユーザー作成
ARG uname
ENV USER_NAME=$uname
ARG uid
ARG gid

RUN useradd -u $uid -o -m $uname && \
    groupmod -g $gid -o $uname && \
    chpasswd ${uname}:defaultpw

### homeディレクトリの設定
RUN export HOME=/home/${uname}

### ホストにマウントする作業ディレクトリ作成
RUN mkdir /home/${uname}/work
WORKDIR /home/${uname}/work

